server:
  port: 9091

spring:
  application:
    name: RESTAURANT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: postgres
    password: suvam123

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

